# -*- coding: utf-8 -*-
"""Project2_CIE555_201901202.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mAgGScGR-G3bz450ZXPu61dMyzAjt876

#YOLOv3
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/YOLO_Project
# %mkdir Yolo3
# %cd /content/drive/MyDrive/YOLO_Project/Yolo3/
!git clone https://github.com/ultralytics/yolov3  # clone
# %cd yolov3
# %pip install -qr requirements.txt  # install

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/YOLO_Project

import time
start = time.time()
!python Yolo3/yolov3/detect.py --weights yolov3.pt --source Test_sample_video.mp4
end = time.time()
time_taken = end - start
print(f'The Time Taken For YOLOv3 Using CPU Is Equal To {round(time_taken,4)} In Seconds')

"""#YOLOv5"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/YOLO_Project
# %mkdir Yolo5
# %cd /content/drive/MyDrive/YOLO_Project/Yolo5/
!git clone https://github.com/ultralytics/yolov5  # clone
# %cd yolov5
!pip install -r requirements.txt  # install

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/YOLO_Project/

start = time.time()
!python Yolo5/yolov5/detect.py --weights yolov5s.pt --source Test_sample_video.mp4 --save-txt
end = time.time()
time_taken2 = end - start
print(f'The Time Taken For YOLOv5 Using CPU Is Equal To {round(time_taken2,4)} In Seconds')

"""#YOLOv8"""

!pip install ultralytics

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/YOLO_Project

!yolo help

start = time.time()
!yolo predict model=yolov8n.pt source=Test_sample_video.mp4 project = '/content/drive/MyDrive/YOLO_Project/Yolo8/'
end = time.time()
time_taken3 = end - start
print(f'The Time Taken For YOLOv8 Using CPU Is Equal To {round(time_taken3,4)} In Seconds')

"""#YOLOv5n"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/YOLO_Project
# %mkdir Yolo5
# %cd /content/drive/MyDrive/YOLO_Project/Yolo5/
!git clone https://github.com/ultralytics/yolov5  # clone
# %cd yolov5
!pip install -r requirements.txt  # install

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/YOLO_Project/

start = time.time()
!python Yolo5/yolov5/detect.py --weights yolov5n.pt --source Test_sample_video.mp4 --save-txt
end = time.time()
time_taken2 = end - start
print(f'The Time Taken For YOLOv5n Using CPU Is Equal To {round(time_taken2,4)} In Seconds')

"""#YOLOv5m"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/YOLO_Project
# %mkdir Yolo5
# %cd /content/drive/MyDrive/YOLO_Project/Yolo5/
!git clone https://github.com/ultralytics/yolov5  # clone
# %cd yolov5
!pip install -r requirements.txt  # install

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/YOLO_Project/

start = time.time()
!python Yolo5/yolov5/detect.py --weights yolov5m.pt --source Test_sample_video.mp4 --save-txt
end = time.time()
time_taken2 = end - start
print(f'The Time Taken For YOLOv5m Using CPU Is Equal To {round(time_taken2,4)} In Seconds')

"""#YOLOv5l"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/YOLO_Project
# %mkdir Yolo5
# %cd /content/drive/MyDrive/YOLO_Project/Yolo5/
!git clone https://github.com/ultralytics/yolov5  # clone
# %cd yolov5
!pip install -r requirements.txt  # install

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/YOLO_Project/

start = time.time()
!python Yolo5/yolov5/detect.py --weights yolov5l.pt --source Test_sample_video.mp4 --save-txt
end = time.time()
time_taken2 = end - start
print(f'The Time Taken For YOLOv5l Using CPU Is Equal To {round(time_taken2,4)} In Seconds')

"""#YOLOv5x"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/YOLO_Project
# %mkdir Yolo5
# %cd /content/drive/MyDrive/YOLO_Project/Yolo5/
!git clone https://github.com/ultralytics/yolov5  # clone
# %cd yolov5
!pip install -r requirements.txt  # install

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/YOLO_Project/

start = time.time()
!python Yolo5/yolov5/detect.py --weights yolov5x.pt --source Test_sample_video.mp4 --save-txt
end = time.time()
time_taken2 = end - start
print(f'The Time Taken For YOLOv5x Using CPU Is Equal To {round(time_taken2,4)} In Seconds')